version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.vite
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:5000/api
      WATCHPACK_POLLING: "true"  # Enable polling for better file watching
    depends_on:
      - server
    command: sh -c "npm run dev -- --host"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/codeforegx
      TIMESCALE_HOST: timescaledb
      TIMESCALE_PORT: 5432
      TIMESCALE_DB: codeforegx_timeseries
      TIMESCALE_USER: postgres
      TIMESCALE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CHOKIDAR_USEPOLLING: "true"  # Enable polling for better file watching
    env_file:
      - .env
    depends_on:
      - mongo
      - timescaledb
      - redis

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codeforegx_timeseries
    volumes:
      - timescale-data:/var/lib/postgresql/data
      - ./database/init/timescale-init.sql:/docker-entrypoint-initdb.d/timescale-init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

volumes:
  mongo-data:
  timescale-data:
  redis-data:
